### ISSUE TITLE
version.texi is missing

### ISSUE THREAD

**Issue by tmalsburg** [ecraven/pinentry-emacs#2]
`make pinentry.texi`fails because version.texi is missing.

I used `./configure --prefix=/home/malsburg/usr/ --enable-pinentry-emacs --enable-inside-emacs --disable-pinentry-qt` on Ubuntu 16.04.

**Comment by ecraven** [comment]
Are you sure you are using this repo? There is no Makefile, no pinentry.texi, nothing like that...

**Comment by tmalsburg** [comment]
Hm, right.  Not sure where I was coming from.  Too long ago.

**Comment by ecraven** [comment]
> Hm, right.  Not sure where I was coming from.  Too long ago.

Might have been gpg/pinentry ;)
